version: '3'

volumes:
  db_data: { }

networks:
  nginx_net:
    external:
      name: nginx_net
  internal: { }

services:
  bot:
    image: fumaz/tts-bot
    container_name: "tts_bot"
    build: .
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
      - ./languages:/usr/src/app/languages
      - ./audios:/usr/src/app/audios
    command: python3 run.py
    networks:
      - internal
      - nginx_net
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: "tts_db"
    environment:
      POSTGRES_DB: 'tts'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped